#pragma once


#define VERSION_MAJOR 0
#define VERSION_MINOR 3
#define VERSION_PATCH 1


#define NONE 0

#pragma region tokenizer_modes
#define INLINE_COMMENT 1
#define BLOCK_COMMENT 2
#define STR_LITERAL 3
#define CHAR_LITERAL 4
#define NUM_LITERAL 5
#define INT_LITERAL 5
#define FLOAT_LITERAL 5
#define DOUBLE_LITERAL 5
#define IDENTIFIER 6
#pragma endregion

#pragma region token_types
#define ACCESS_TOK 1
#define ACTION_TOK 2
#define ARROW_TOK 3
#define ASSIGNMENT_TOK 4
#define CHAR_TOK 5
#define CONTEXT_TOK 6
#define DECREMENT_TOK 7
#define DOUBLE_TOK 8
#define EQUALITY_OPERATOR_TOK 9
#define FLOAT_TOK 10
#define IDENTIFIER_TOK 11
#define INCREMENT_TOK 12
#define INT_TOK 13
#define LOGICAL_OPERATOR_TOK 14
#define MATHEMATICAL_OPERATOR_TOK 15
#define POST_DECREMENT_TOK 16
#define POST_INCREMENT_TOK 17
#define PRE_DECREMENT_TOK 18
#define PRE_INCREMENT_TOK 19
#define SEPARATOR_TOK 20
#define STAR_TOK 21
#define STRING_TOK 22
#define TERMINATOR_TOK 23
#define TERNARY_TOK 24

#define RESERVED_ALIGNAS 25
#define RESERVED_ALIGNOF 26
#define RESERVED_AND 27
#define RESERVED_ASSERT 28
#define RESERVED_BOOL 29
#define RESERVED_BREAK 30
#define RESERVED_CASE 31
#define RESERVED_CATCH 32
#define RESERVED_CHAR 33
#define RESERVED_CLASS 34
#define RESERVED_CONST 35
#define RESERVED_CONSTEXPR 36
#define RESERVED_CONST_CAST 37
#define RESERVED_CONTINUE 38
#define RESERVED_DECLTYPE 39
#define RESERVED_DEFAULT 40
#define RESERVED_DELETE 41
#define RESERVED_DOUBLE 42
#define RESERVED_DYNAMIC_CAST 43
#define RESERVED_ELSE 44
#define RESERVED_ENUM 45
#define RESERVED_EXPLICIT 46
#define RESERVED_EXPORT 47
#define RESERVED_FALSE 48
#define RESERVED_FINAL 49
#define RESERVED_FLOAT 50
#define RESERVED_FOR 51
#define RESERVED_FRIEND 52
#define RESERVED_FROM 53
#define RESERVED_IDENTIFIER 54
#define RESERVED_IF 55
#define RESERVED_IMPORT 56
#define RESERVED_INLINE 57
#define RESERVED_INT 58
#define RESERVED_LONG 59
#define RESERVED_MODULE 60
#define RESERVED_MUTABLE 61
#define RESERVED_NAMESPACE 62
#define RESERVED_NEW 63
#define RESERVED_NIL 64
#define RESERVED_NOEXCEPT 65
#define RESERVED_NOT 66
#define RESERVED_NULLPTR 67
#define RESERVED_OR 68
#define RESERVED_OVERRIDE 69
#define RESERVED_PRINT 70
#define RESERVED_PRIVATE 71
#define RESERVED_PROTECTED 72
#define RESERVED_PUBLIC 73
#define RESERVED_REGISTER 74
#define RESERVED_REINTERPRET_CAST 75
#define RESERVED_REQUIRES 76
#define RESERVED_RETURN 77
#define RESERVED_SHORT 78
#define RESERVED_SIGNED 79
#define RESERVED_STATIC 80
#define RESERVED_STATIC_CAST 81
#define RESERVED_STR 82
#define RESERVED_STRUCT 83
#define RESERVED_SUPER 84
#define RESERVED_SWITCH 85
#define RESERVED_TEMPLATE 86
#define RESERVED_THIS 87
#define RESERVED_THREAD_LOCAL 88
#define RESERVED_TRUE 89
#define RESERVED_TRY 90
#define RESERVED_TYPENAME 91
#define RESERVED_TYPEOF 92
#define RESERVED_UNION 93
#define RESERVED_UNSIGNED 94
#define RESERVED_VIRTUAL 95
#define RESERVED_VOID 96
#define RESERVED_VOLATILE 97
#define RESERVED_WHILE 98
#define RESERVED_WITH 99
#pragma endregion

#pragma region errors
#define FILE_NOT_FOUND 1
#define ERROR_OCCURED 10
#define INVALID_ARGS 28
#define UNTERMINATED_STR 34
#define MALFORMED_CHAR 35
#define UNEXPECTED_CHAR 36
#define UNTERMINATED_PARENTHESES 41
#define ERROR_OCCURED_IN_TOKENIZATION 65
#define ERROR_OCCURED_IN_PARSING 66
#define UNTERMINATED_BRACKET 93
#define UNTERMINATED_BRACE 125
#define UNIMPLEMENTED 254
#define UNIMPLEMENTED_FEATURE 255
#pragma endregion

#include <cstddef>
#include <cstring>
#include <iostream>
#include <ostream>
#include <sstream>
#include <array>

#include "miscellaneous.h"