#pragma once

#define NONE 0

#pragma region tokenizer_modes
#define INLINE_COMMENT 1
#define STR_LITERAL 2
#define NUM_LITERAL 3
#define INT_LITERAL 3
#define FLOAT_LITERAL 3
#define IDENTIFIER 4
#pragma endregion

#pragma region token_types
#define INT_TOK 1
#define FLOAT_TOK 2
#define IDENTIFIER_TOK 3
#define STRING_TOK 4
#define EQUALITY_OPERATOR_TOK 5
#define LOGICAL_OPERATOR_TOK 6
#define MATHEMATICAL_OPERATOR_TOK 7
#define CONTEXT_TOK 8
#define ASSIGNMENT_TOK 9
#define STAR_TOK 10
#define TERNARY_TOK 11
#define SEPARATOR_TOK 12
#define TERMINATOR_TOK 13
#define ACCESS_TOK 14
#define ACTION_TOK 15

#define RESERVED_AND 16
#define RESERVED_OR 17
#define RESERVED_IF 18
#define RESERVED_ELSE 19
#define RESERVED_CLASS 20
#define RESERVED_NIL 21
#define RESERVED_FOR 22
#define RESERVED_WHILE 23
#define RESERVED_PRINT 24
#define RESERVED_SUPER 25
#define RESERVED_THIS 26
#define RESERVED_RETURN 27
#define RESERVED_VOID 28
#define RESERVED_STRUCT 29
#define RESERVED_ENUM 30
#define RESERVED_INT 31
#define RESERVED_FLOAT 32
#define RESERVED_DOUBLE 33
#define RESERVED_CHAR 34
#define RESERVED_STR 35
#define RESERVED_BOOL 36
#define RESERVED_TRUE 37
#define RESERVED_FALSE 38
#define RESERVED_IDENTIFIER 39
#define RESERVED_PUBLIC 40
#define RESERVED_PRIVATE 41
#define RESERVED_PROTECTED 42
#define RESERVED_CONTINUE 43
#define RESERVED_BREAK 44
#define RESERVED_UNION 45
#define RESERVED_LONG 46
#define RESERVED_SHORT 47
#define RESERVED_SIGNED 48
#define RESERVED_UNSIGNED 49
#define RESERVED_SWITCH 50
#define RESERVED_CASE 51
#define RESERVED_DEFAULT 52
#define RESERVED_DELETE 53
#define RESERVED_MUTABLE 54
#define RESERVED_CONST 55
#define RESERVED_CONSTEXPR 56
#define RESERVED_FRIEND 57
#define RESERVED_VIRTUAL 58
#define RESERVED_FINAL 59
#define RESERVED_OVERRIDE 60
#define RESERVED_NEW 61
#define RESERVED_NAMESPACE 62
#define RESERVED_TYPEOF 63
#define RESERVED_ASSERT 64
#define RESERVED_TEMPLATE 65
#define RESERVED_TYPENAME 66
#define RESERVED_REGISTER 67
#define RESERVED_VOLATILE 68
#define RESERVED_STATIC 69
#define RESERVED_INLINE 70
#define RESERVED_ALIGNAS 71
#define RESERVED_ALIGNOF 72
#define RESERVED_NOEXCEPT 73
#define RESERVED_DECLTYPE 74
#define RESERVED_NULLPTR 75
#define RESERVED_THREAD_LOCAL 76
#define RESERVED_STATIC_CAST 77
#define RESERVED_DYNAMIC_CAST 78
#define RESERVED_REINTERPRET_CAST 79
#define RESERVED_CONST_CAST 80
#define RESERVED_TRY 81
#define RESERVED_CATCH 82
#define RESERVED_EXPLICIT 83
#define RESERVED_EXPORT 84
#define RESERVED_IMPORT 85
#define RESERVED_MODULE 86
#define RESERVED_REQUIRES 87
#define RESERVED_WITH 88
#define RESERVED_FROM 89
#pragma endregion

#pragma region errors
#define FILE_NOT_FOUND 1
#define INVALID_ARG 28
#define UNTERMINATED_STR 34
#define UNEXPECTED_CHAR 36
#define UNTERMINATED_PARENTHESES 41
#define ERROR_OCCURED_IN_TOKENIZATION 65
#define UNTERMINATED_BRACKET 93
#define UNTERMINATED_BRACE 125
#pragma endregion

#include <cstddef>
#include <cstring>
#include <iostream>
#include <ostream>
#include <sstream>
#include <string>
#include <vector>